name: CDKTF Python Action

on:
  push:
    branches:
      - prod
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - prod

jobs:
  build_and_deploy_job:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: "Evaluate the pull request (Terraform plan)"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pipenv
        run: |
          pip install pipenv
      - name: Install cdktf
        run: |
          npm install --location=global cdktf-cli@latest
      - name: Install dependencies
        run: |
          pipenv install
      - name: Execute plan
        env:
          AzureClientID: ${{ secrets.AzureClientID }}
          AzureTenantID: ${{ secrets.AzureTenantID }}
          AzureSubscriptionID: ${{ secrets.AzureSubscriptionID }}
          AzureClientSecret: ${{ secrets.AzureClientSecret }}
          TerraformToken: ${{ secrets.TerraformToken }}
        run: |
          cdktf plan

  close_pull_request_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: "Deploy de infraestructure (Terraform apply)"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pipenv
        run: |
          pip install pipenv
      - name: Install cdktf
        run: |
          npm install --location=global cdktf-cli@latest
      - name: Install dependencies
        run: |
          pipenv install
      - name: Execute plan
        env:
          AzureClientID: ${{ secrets.AzureClientID }}
          AzureTenantID: ${{ secrets.AzureTenantID }}
          AzureSubscriptionID: ${{ secrets.AzureSubscriptionID }}
          AzureClientSecret: ${{ secrets.AzureClientSecret }}
          TerraformToken: ${{ secrets.TerraformToken }}
        run: |
          cdktf deploy
